# Generated by Django 3.2.12 on 2023-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
                ('cantPag', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
