# Generated by Django 3.2.12 on 2023-01-31 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaLibros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newbook',
            old_name='autor',
            new_name='autorD',
        ),
        migrations.RenameField(
            model_name='newbook',
            old_name='cantPag',
            new_name='cantPagD',
        ),
        migrations.RenameField(
            model_name='newbook',
            old_name='precio',
            new_name='precioD',
        ),
        migrations.RenameField(
            model_name='newbook',
            old_name='titulo',
            new_name='tituloD',
        ),
        migrations.RenameField(
            model_name='newbook',
            old_name='year',
            new_name='yearD',
        ),
    ]
